service: nelcm-record-manager-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  architecture: x86_64
  httpApi:
    cors: true
  environment:
    LD_LIBRARY_PATH: /var/task/lib
    ODBCSYSINI: /var/task
    SQS_QUEUE_URL: !Ref RenewalEmailQueue
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
        # --- REMOVE THE SQS PERMISSION FROM HERE ---

  vpc:
    securityGroupIds:
      - sg-0538cfedbe5d23eb5
    subnetIds:
      - subnet-06ca61fce5f705db2
      - subnet-01ae22cae3a9c51f5

functions:
  api:
    image: ${param:image}
    timeout: 15
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any

  renewalEmailTrigger:
    image:
      uri: ${param:image}
      command:
        - renewal_trigger.handler
    events:
      - schedule: cron(0 12 1 * ? *)

  sesHandler:
    image:
      uri: ${param:image}
      command:
        - ses_handler.handler
    events:
      - sns: nelcm-ses-events

  emailSender:
    image:
      uri: ${param:image}
      command:
        - email_sender.handler
    timeout: 15
    events:
      - sqs:
          arn: !GetAtt RenewalEmailQueue.Arn
          batchSize: 5
    # --- ADD THE SPECIFIC PERMISSION AND DEPENDSON HERE ---
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
        Resource: !GetAtt RenewalEmailQueue.Arn
    dependsOn:
      - RenewalEmailQueue

resources:
  Resources:
    RenewalEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${sls:stage}-renewal-email-queue