# serverless.yml

service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

  # CORS configuration for HTTP APIs goes here
  httpApi:
    cors: true

  # Defines the permissions for the Lambda function
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          # Allows access to the specific secret for your database
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

package:
  # Excludes unnecessary files to keep the deployment package small
  patterns:
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.git/**'
    - '!.venv/**'

functions:
  # This is the main function that will run your Flask app
  api:
    handler: lambda.handler # Points to the handler function in lambda.py
    events:
      - httpApi: # The cors line is removed from here
          path: /api/{proxy+}
          method: any