service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any

package:
  # This tells Serverless to use a zip file we will create, instead of building its own.
  artifact: artifact.zip