service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  environment:
    LD_LIBRARY_PATH: /var/task/lib
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

functions:
  api:
    image:
      name: appimage
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any