service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  environment:
    LD_LIBRARY_PATH: /var/task/lib
    ODBCSYSINI: /var/task
    SQS_QUEUE_URL: !Ref RenewalEmailQueue
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource: !GetAtt RenewalEmailQueue.Arn
  
  # CORRECTED PLACEMENT: vpc is a direct child of provider
  vpc:
    securityGroupIds:
      - sg-0538cfedbe5d23eb5
    subnetIds:
      - subnet-06ca61fce5f705db2
      - subnet-01ae22cae3a9c51f5

functions:
  api:
    image:
      name: appimage
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any
          
  renewalEmailTrigger:
    image:
      name: appimage # Reuse the same ECR image
      command:
        - renewal_trigger.handler # Correctly override the Docker CMD for this function
    events:
      - schedule: cron(0 12 1 * ? *) # Runs at 12:00 PM UTC on the 1st day of every month
      
  sesHandler:
    image:
      name: appimage # Reuse the same ECR image
      command:
        - ses_handler.handler # Point to the new handler
    events:
      - sns: nelcm-ses-events # Subscribe to this SNS topic
      
  emailSender:
    image:
      name: appimage
      command:
        - email_sender.handler # Points to the new handler file
    events:
      # This function is triggered by messages on the SQS queue
      - sqs:
          arn: !GetAtt RenewalEmailQueue.Arn
          batchSize: 5 # Process up to 5 emails at a time
          
resources:
  Resources:
    RenewalEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: renewal-email-queue