service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  environment:
    LD_LIBRARY_PATH: /var/task/lib
    ODBCSYSINI: /var/task
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
  
  # CORRECTED PLACEMENT: vpc is a direct child of provider
  vpc:
    securityGroupIds:
      - sg-0538cfedbe5d23eb5 # Replace with your Security Group ID
      - sg-087d696b0a5c38093
    subnetIds:
      - subnet-0c28480ffa2575501 # Replace with your first Subnet ID
      - subnet-06b38eab5381ea78f # Replace with your second Subnet ID

functions:
  api:
    image:
      name: appimage
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any
          
  renewalEmailTrigger:
    image:
      name: appimage # Reuse the same ECR image
      command:
        - renewal_trigger.handler # Correctly override the Docker CMD for this function
    events:
      - schedule: cron(0 12 1 * ? *) # Runs at 12:00 PM UTC on the 1st day of every month