service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  environment:
    LD_LIBRARY_PATH: /var/task/lib
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"
  vpc:
    securityGroupIds:
      - sg-0538cfedbe5d23eb5 # Replace with your Security Group ID
      - sg-087d696b0a5c38093
      
    subnetIds:
      - subnet-0c28480ffa2575501 # Replace with your first Subnet ID
      - subnet-06b38eab5381ea78f # Replace with your second Subnet ID
  environment:
   LD_LIBRARY_PATH: /var/task/lib
   ODBCSYSINI: /var/task

functions:
  api:
    image:
      name: appimage
    timeout: 5
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any
          
          
