service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  
  # This tells Lambda where to find the driver files at runtime
  environment:
    LD_LIBRARY_PATH: /var/task/lib

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any

package:
  artifact: artifact.zip