# serverless.yml

service: nelcm-record-manager-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

package:
  patterns:
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.git/**'
    - '!.venv/**'

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any
          cors: true # This line solves the CORS error