service: nelcm-record-manager-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  architecture: x86_64
  # Assign the explicitly defined role to all functions
  iam:
    role: IamRoleLambdaExecution
  httpApi:
    cors: true
    authorizers:
      cognitoJwt:
        type: jwt
        identitySource: "$request.header.Authorization"
        issuerUrl: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DbvqrCJkl"
        audience:
          - "kd7ovn5929vlj8fpi1f7gvbv4"
          
  environment:
    LD_LIBRARY_PATH: /var/task/lib
    ODBCSYSINI: /var/task
    SQS_QUEUE_URL: !Ref RenewalEmailQueue

  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64

  vpc:
    securityGroupIds:
      - sg-0538cfedbe5d23eb5

    subnetIds:
      - subnet-06ca61fce5f705db2
      - subnet-01ae22cae3a9c51f5

functions:
  api:
    image: appimage
    timeout: 5
    events:
      - httpApi: 'ANY /api/{proxy+}'
        authorizer:
            name: cognitoJwt


  renewalEmailTrigger:
    image:
      name: appimage
      command:
        - renewal_trigger.handler
    events:
      - schedule: cron(0 12 1 * ? *)
      
  renewalMailer:
    handler: renewal_trigger.handler
    events:
      - http:
          path: renewals/run
          method: post

  sesHandler:
    image:
      name: appimage
      command:
        - ses_handler.handler
    events:
      - sns: nelcm-ses-events

  emailSender:
    image:
      name: appimage
      command:
        - email_sender.handler
    timeout: 15
    events:
      - sqs:
          arn: !GetAtt RenewalEmailQueue.Arn
          batchSize: 5

resources:
  Resources:
    RenewalEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${sls:stage}-renewal-email-queue

    IamRoleLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${sls:stage}-lambda-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
              
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: ${self:service}-${sls:stage}-lambda-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "secretsmanager:GetSecretValue"
                  Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"
                - Effect: Allow
                  Action:
                    - "ses:SendEmail"
                    - "ses:SendRawEmail"
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - "sqs:SendMessage"
                    - "sqs:ReceiveMessage" # emailSender needs this permission too
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                  Resource: !GetAtt RenewalEmailQueue.Arn
      DependsOn:
        - RenewalEmailQueue