service: nelcm-record-manager-api

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    # This builds dependencies inside a Docker container that matches the
    # Lambda environment. It's crucial for libraries like pyodbc.
    dockerizePip: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:nelcm-db-*"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: any
          cors: true

package:
  # Explicitly include only what's needed
  patterns:
    - 'app.py'
    - 'lambda.py'
    - 'requirements.txt'
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.git/**'
    - '!.venv/**'