# .github/workflows/deploy.yml

name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    
    steps:
      # 1. Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Create the ZIP deployment package
      - name: Create ZIP file for deployment
        run: zip deploy.zip app.py index.html logo.png requirements.txt

      # 5. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # The region for your Elastic Beanstalk environment

      # 6. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          # --- YOU MUST CHANGE THESE VALUES ---
          application_name: 'nelcm-record-manager' # Your Elastic Beanstalk Application Name
          environment_name: 'nelcm-record-manager-env' # Your Elastic Beanstalk Environment Name
          # ------------------------------------
          
          region: us-east-1 # The same region as above
          version_label: "${{ github.sha }}-${{ github.run_number }}" # Creates a unique version label
          deployment_package: deploy.zip # The zip file created in step 4